## Importing libraries

In [2]:
import pandas as pd
import json

## Reading data

In [67]:
visitors = pd.read_csv("../source/visitors.csv")
answers = pd.read_csv("../source/visitors_answers.csv")
questions = pd.read_csv("../source/visitors_questions.csv")
exhibitors = pd.read_csv("../source/exhibitors.csv")
categories = pd.read_csv("../source/exhibitor_categories.csv")

Sampling 5 records from each dataset

In [68]:
print("visitors:", visitors.shape)
visitors.head()

visitors: (100, 4)

,email,gender,id,data
0,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,"[{ ""stepId"" : ""5c8a78336d41a10da4f730ef"", ""que..."
1,aleksandar.dimkov+mitt1_n5eA@bss.com.mk,M,67ada1ee197e604dd2722d1b,"[{ ""stepId"" : ""5c8a78336d41a10da4f730ef"", ""que..."
2,daniela.p+150_YhiF@bss.com.mk,F,67b44fef197e604dd2722d3d,"[{ ""stepId"" : ""5c8a78336d41a10da4f730ef"", ""que..."
3,tanja+182_jiPa@bss.com.mk,F,67b45018197e604dd2722d3e,"[{ ""stepId"" : ""5c8a78336d41a10da4f730ef"", ""que..."
4,aleksandar.dimkov+mitt10_V0iB@bss.com.mk,M,67b5f1392d21f543a10965f1,"[{ ""stepId"" : ""5c8a78336d41a10da4f730ef"", ""que..."

In [69]:
visitors.rename({'id': 'visitorId'}, axis=1, inplace=True) # To prevent confusion later
visitors.head()

,email,gender,visitorId,data
0,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,"[{ ""stepId"" : ""5c8a78336d41a10da4f730ef"", ""que..."
1,aleksandar.dimkov+mitt1_n5eA@bss.com.mk,M,67ada1ee197e604dd2722d1b,"[{ ""stepId"" : ""5c8a78336d41a10da4f730ef"", ""que..."
2,daniela.p+150_YhiF@bss.com.mk,F,67b44fef197e604dd2722d3d,"[{ ""stepId"" : ""5c8a78336d41a10da4f730ef"", ""que..."
3,tanja+182_jiPa@bss.com.mk,F,67b45018197e604dd2722d3e,"[{ ""stepId"" : ""5c8a78336d41a10da4f730ef"", ""que..."
4,aleksandar.dimkov+mitt10_V0iB@bss.com.mk,M,67b5f1392d21f543a10965f1,"[{ ""stepId"" : ""5c8a78336d41a10da4f730ef"", ""que..."

email, gender and id columns are standard whereas data seems to have packed information (probably JSON). Need to dive deeper into this.

In [70]:
print("answers:", answers.shape)
answers.head()

answers: (43, 3)

,id,answer,questionId
0,5c8a78336d41a10da4f73103,Personal interest,5c8a78336d41a10da4f730fe
1,5c8a78336d41a10da4f73100,To obtain general information,5c8a78336d41a10da4f730fe
2,5c8a78336d41a10da4f730ff,To source products and services,5c8a78336d41a10da4f730fe
3,5c8a78336d41a10da4f73101,To promote products and services,5c8a78336d41a10da4f730fe
4,5c8a78336d41a10da4f73102,Educational purposes,5c8a78336d41a10da4f730fe

In [71]:
answers.rename({'id': 'answerId'}, axis=1, inplace=True) # To prevent confusion later
answers.head()

,answerId,answer,questionId
0,5c8a78336d41a10da4f73103,Personal interest,5c8a78336d41a10da4f730fe
1,5c8a78336d41a10da4f73100,To obtain general information,5c8a78336d41a10da4f730fe
2,5c8a78336d41a10da4f730ff,To source products and services,5c8a78336d41a10da4f730fe
3,5c8a78336d41a10da4f73101,To promote products and services,5c8a78336d41a10da4f730fe
4,5c8a78336d41a10da4f73102,Educational purposes,5c8a78336d41a10da4f730fe

Fairly straightforward answerID, answer and questionID

In [72]:
print("questions:", questions.shape)
questions.head()

questions: (5, 4)

,id,questionTypeId,stepId,question
0,5c8a78336d41a10da4f730fe,5bf7c399b82beb7a182cc3de,5c8a78336d41a10da4f730fd,Reason for Attending the Event
1,5c8a78336d41a10da4f73253,5bf7c399b82beb7a182cc3de,5c8a78336d41a10da4f73252,Please indicate your company's main area of bu...
2,5c8a78336d41a10da4f7336d,5bf7c399b82beb7a182cc3de,5c8a78336d41a10da4f7336c,What role do you play in the purchasing decisi...
3,5c8a78336d41a10da4f73372,5bf7c399b82beb7a182cc3de,5c8a78336d41a10da4f7336c,What is your company's annual purchasing budget?
4,5c8a78336d41a10da4f73227,5bf7c399b82beb7a182cc3de,5c8a78336d41a10da4f73225,Which of the following best describes your job...

In [73]:
questions.rename({'id': 'questionId'}, axis=1, inplace=True) # To prevent confusion later
questions.head()

,questionId,questionTypeId,stepId,question
0,5c8a78336d41a10da4f730fe,5bf7c399b82beb7a182cc3de,5c8a78336d41a10da4f730fd,Reason for Attending the Event
1,5c8a78336d41a10da4f73253,5bf7c399b82beb7a182cc3de,5c8a78336d41a10da4f73252,Please indicate your company's main area of bu...
2,5c8a78336d41a10da4f7336d,5bf7c399b82beb7a182cc3de,5c8a78336d41a10da4f7336c,What role do you play in the purchasing decisi...
3,5c8a78336d41a10da4f73372,5bf7c399b82beb7a182cc3de,5c8a78336d41a10da4f7336c,What is your company's annual purchasing budget?
4,5c8a78336d41a10da4f73227,5bf7c399b82beb7a182cc3de,5c8a78336d41a10da4f73225,Which of the following best describes your job...

There seem to be 5 questions. Each question has a questionID, questionTypeID, stepID. (We saw questionID before already, not sure if the other 2 IDs are relevant yet..)

In [74]:
print("exhibitors:", exhibitors.shape)
exhibitors.head()

exhibitors: (35, 3)

   exhibitorid                    Name                       MainCategories
0        90556          Turkey Travels                    52276|52280|52281
1        92462  Russian Travel Company  52273|52283|52289|52291|52298|52302
2        92491   Indian Travel Company                    52273|52274|52281
3        92492            Asia Tourism              52272|52276|52352|52358
4        92493     SriLanka Adventures                    52296|52327|52352

In [75]:
exhibitors.rename({'exhibitorid': 'exhibitorId'}, axis=1, inplace=True) # To standardize column names
exhibitors.head()

   exhibitorId                    Name                       MainCategories
0        90556          Turkey Travels                    52276|52280|52281
1        92462  Russian Travel Company  52273|52283|52289|52291|52298|52302
2        92491   Indian Travel Company                    52273|52274|52281
3        92492            Asia Tourism              52272|52276|52352|52358
4        92493     SriLanka Adventures                    52296|52327|52352

Each exhibitor has a name, and ID and their selected list of categories.

In [76]:
print("categories:", categories.shape)
categories.head()

categories: (96, 2)

   categoryId                        categoryName
0       52271           1. Accomodation providers
1       52272       1.1 Hotel / Hotel chain / Inn
2       52273  1.2 Apartments / Residential hotel
3       52274                  1.3 Hostel / Motel
4       52275                  1.4 Boarding house

Mapping of categoryID to its name

## Data cleaning and processing

### Performing basic sanity checks on each dataset

In [11]:
visitors.info()
visitors.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   email   100 non-null    object
 1   gender  100 non-null    object
 2   id      100 non-null    object
 3   data    100 non-null    object
dtypes: object(4)
memory usage: 3.2+ KB

email     0
gender    0
id        0
data      0
dtype: int64

In [12]:
answers.info()
answers.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          43 non-null     object
 1   answer      43 non-null     object
 2   questionId  43 non-null     object
dtypes: object(3)
memory usage: 1.1+ KB

id            0
answer        0
questionId    0
dtype: int64

In [13]:
questions.info()
questions.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              5 non-null      object
 1   questionTypeId  5 non-null      object
 2   stepId          5 non-null      object
 3   question        5 non-null      object
dtypes: object(4)
memory usage: 288.0+ bytes

id                0
questionTypeId    0
stepId            0
question          0
dtype: int64

In [14]:
exhibitors.info()
exhibitors.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   exhibitorid     35 non-null     int64
 1   Name            35 non-null     object
 2   MainCategories  35 non-null     object
dtypes: int64(1), object(2)
memory usage: 968.0+ bytes

exhibitorid       0
Name              0
MainCategories    0
dtype: int64

In [15]:
categories.info()
categories.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   categoryId    96 non-null     int64
 1   categoryName  96 non-null     object
dtypes: int64(1), object(1)
memory usage: 1.6+ KB

categoryId      0
categoryName    0
dtype: int64

All the datasets seem to be clean as of now.

### Processing the data and trying to make sense of it all

#### Understanding the visitors dataset

In [77]:
print(visitors.data.loc[0])

[{ "stepId" : "5c8a78336d41a10da4f730ef", "questionId" : "5c8a78336d41a10da4f730f0", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f730f2", "answerTypeId" : "Answer" }, { "stepId" : "6507da8d9e117216630ef7ed", "questionId" : "6507de7e9e117216630ef7f2", "answerValue" : "emilija+100_L8gA@bss.mk", "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "6507dfbb9e117216630ef7f3", "questionId" : "6507e0219e117216630ef7f5", "answerValue" : "3138", "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f733ce", "questionId" : "5c8a78336d41a10da4f733d8", "answerValue" : "Eme", "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f733ce", "questionId" : "5c8a78336d41a10da4f733e2", "answerValue" : "Jankova", "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f733ce", "questionId" : "5c8a78336d41a10da4f733cf", "answerValue" : "Emilija", "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f733ce", "questionId" : "5c8a78336d41a10da4f733d9", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f733de", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f730f3", "questionId" : "5c8a78336d41a10da4f730f4", "answerValue" : "Russia", "answerId" : "5c8a78346d41a10da4f7348e", "answerTypeId" : "Country" }, { "stepId" : "5c8a78336d41a10da4f730f3", "questionId" : "5c8a78336d41a10da4f730f4", "answerValue" : "Komi Republic", "answerId" : "5c8a78346d41a10da4f734a6", "answerTypeId" : "Region" }, { "stepId" : "5c8a78336d41a10da4f730f3", "questionId" : "5c8a78336d41a10da4f730f5", "answerValue" : "Komi", "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f730f3", "questionId" : "5c8a78336d41a10da4f730fb", "answerValue" : "Ivo Ribar Lola 54a", "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f730f3", "questionId" : "5c8a78336d41a10da4f730fc", "answerValue" : "78877665", "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f730f3", "questionId" : "5c8a78336d41a10da4f730f7", "answerValue" : true, "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f730f3", "questionId" : "5d7a4eb1bd2e7e3e64f57a25", "answerValue" : true, "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f730fd", "questionId" : "5c8a78336d41a10da4f730fe", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f73100", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f730fd", "questionId" : "5c8a78336d41a10da4f73104", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f7315f", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f730fd", "questionId" : "5c8a78336d41a10da4f73104", "answerValue" : "", "answerId" : "67acad10197e604dd2722d08", "answerTypeId" : "Answer" }, { "stepId" : "65a51b5a097d28c29bcb7403", "questionId" : "65a51b7a097d28c29bcb7404", "answerValue" : "", "answerId" : "65a51b87097d28c29bcb7405", "answerTypeId" : "Answer" }, { "stepId" : "65a51b5a097d28c29bcb7403", "questionId" : "65a51b7a097d28c29bcb7404", "answerValue" : "", "answerId" : "65a51b9a097d28c29bcb7406", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73225", "questionId" : "5c8a78336d41a10da4f7324a", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f7324e", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73225", "questionId" : "5c8a78336d41a10da4f73227", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f73244", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73225", "questionId" : "5c8a78336d41a10da4f73226", "answerValue" : "BSS", "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73225", "questionId" : "5c8a78336d41a10da4f73250", "answerValue" : "tester", "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73252", "questionId" : "5c8a78336d41a10da4f73253", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f73291", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73252", "questionId" : "5c8a78336d41a10da4f7334e", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f7334f", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73252", "questionId" : "5c8a78336d41a10da4f7334e", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f73350", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73252", "questionId" : "5c8a78336d41a10da4f73326", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f73334", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73252", "questionId" : "5c8a78336d41a10da4f73358", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f73359", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73252", "questionId" : "5c8a78336d41a10da4f73358", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f7335b", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73252", "questionId" : "5c8a78336d41a10da4f73358", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f7335c", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73252", "questionId" : "5c8a78336d41a10da4f732ed", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f732ef", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f7336c", "questionId" : "5c8a78336d41a10da4f7336d", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f73371", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f7337a", "questionId" : "5c8a78336d41a10da4f7337b", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f7337c", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f7337a", "questionId" : "5c8a78336d41a10da4f7337e", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f7337f", "answerTypeId" : "Answer" }]

In [78]:

#Inspecting a single record
sample_json = json.loads(visitors['data'].loc[0])

print(sample_json)
print("Length of data: {}".format(len(sample_json)))
print("Example of one data point: {}".format(sample_json[0]))

[{'stepId': '5c8a78336d41a10da4f730ef', 'questionId': '5c8a78336d41a10da4f730f0', 'answerValue': '', 'answerId': '5c8a78336d41a10da4f730f2', 'answerTypeId': 'Answer'}, {'stepId': '6507da8d9e117216630ef7ed', 'questionId': '6507de7e9e117216630ef7f2', 'answerValue': 'emilija+100_L8gA@bss.mk', 'answerId': '', 'answerTypeId': 'Answer'}, {'stepId': '6507dfbb9e117216630ef7f3', 'questionId': '6507e0219e117216630ef7f5', 'answerValue': '3138', 'answerId': '', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f733ce', 'questionId': '5c8a78336d41a10da4f733d8', 'answerValue': 'Eme', 'answerId': '', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f733ce', 'questionId': '5c8a78336d41a10da4f733e2', 'answerValue': 'Jankova', 'answerId': '', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f733ce', 'questionId': '5c8a78336d41a10da4f733cf', 'answerValue': 'Emilija', 'answerId': '', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f733ce', 'questionId': '5c8a78336d41a10da4f733d9', 'answerValue': '', 'answerId': '5c8a78336d41a10da4f733de', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f730f3', 'questionId': '5c8a78336d41a10da4f730f4', 'answerValue': 'Russia', 'answerId': '5c8a78346d41a10da4f7348e', 'answerTypeId': 'Country'}, {'stepId': '5c8a78336d41a10da4f730f3', 'questionId': '5c8a78336d41a10da4f730f4', 'answerValue': 'Komi Republic', 'answerId': '5c8a78346d41a10da4f734a6', 'answerTypeId': 'Region'}, {'stepId': '5c8a78336d41a10da4f730f3', 'questionId': '5c8a78336d41a10da4f730f5', 'answerValue': 'Komi', 'answerId': '', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f730f3', 'questionId': '5c8a78336d41a10da4f730fb', 'answerValue': 'Ivo Ribar Lola 54a', 'answerId': '', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f730f3', 'questionId': '5c8a78336d41a10da4f730fc', 'answerValue': '78877665', 'answerId': '', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f730f3', 'questionId': '5c8a78336d41a10da4f730f7', 'answerValue': True, 'answerId': '', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f730f3', 'questionId': '5d7a4eb1bd2e7e3e64f57a25', 'answerValue': True, 'answerId': '', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f730fd', 'questionId': '5c8a78336d41a10da4f730fe', 'answerValue': '', 'answerId': '5c8a78336d41a10da4f73100', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f730fd', 'questionId': '5c8a78336d41a10da4f73104', 'answerValue': '', 'answerId': '5c8a78336d41a10da4f7315f', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f730fd', 'questionId': '5c8a78336d41a10da4f73104', 'answerValue': '', 'answerId': '67acad10197e604dd2722d08', 'answerTypeId': 'Answer'}, {'stepId': '65a51b5a097d28c29bcb7403', 'questionId': '65a51b7a097d28c29bcb7404', 'answerValue': '', 'answerId': '65a51b87097d28c29bcb7405', 'answerTypeId': 'Answer'}, {'stepId': '65a51b5a097d28c29bcb7403', 'questionId': '65a51b7a097d28c29bcb7404', 'answerValue': '', 'answerId': '65a51b9a097d28c29bcb7406', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f73225', 'questionId': '5c8a78336d41a10da4f7324a', 'answerValue': '', 'answerId': '5c8a78336d41a10da4f7324e', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f73225', 'questionId': '5c8a78336d41a10da4f73227', 'answerValue': '', 'answerId': '5c8a78336d41a10da4f73244', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f73225', 'questionId': '5c8a78336d41a10da4f73226', 'answerValue': 'BSS', 'answerId': '', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f73225', 'questionId': '5c8a78336d41a10da4f73250', 'answerValue': 'tester', 'answerId': '', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f73252', 'questionId': '5c8a78336d41a10da4f73253', 'answerValue': '', 'answerId': '5c8a78336d41a10da4f73291', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f73252', 'questionId': '5c8a78336d41a10da4f7334e', 'answerValue': '', 'answerId': '5c8a78336d41a10da4f7334f', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f73252', 'questionId': '5c8a78336d41a10da4f7334e', 'answerValue': '', 'answerId': '5c8a78336d41a10da4f73350', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f73252', 'questionId': '5c8a78336d41a10da4f73326', 'answerValue': '', 'answerId': '5c8a78336d41a10da4f73334', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f73252', 'questionId': '5c8a78336d41a10da4f73358', 'answerValue': '', 'answerId': '5c8a78336d41a10da4f73359', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f73252', 'questionId': '5c8a78336d41a10da4f73358', 'answerValue': '', 'answerId': '5c8a78336d41a10da4f7335b', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f73252', 'questionId': '5c8a78336d41a10da4f73358', 'answerValue': '', 'answerId': '5c8a78336d41a10da4f7335c', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f73252', 'questionId': '5c8a78336d41a10da4f732ed', 'answerValue': '', 'answerId': '5c8a78336d41a10da4f732ef', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f7336c', 'questionId': '5c8a78336d41a10da4f7336d', 'answerValue': '', 'answerId': '5c8a78336d41a10da4f73371', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f7337a', 'questionId': '5c8a78336d41a10da4f7337b', 'answerValue': '', 'answerId': '5c8a78336d41a10da4f7337c', 'answerTypeId': 'Answer'}, {'stepId': '5c8a78336d41a10da4f7337a', 'questionId': '5c8a78336d41a10da4f7337e', 'answerValue': '', 'answerId': '5c8a78336d41a10da4f7337f', 'answerTypeId': 'Answer'}]
Length of data: 34
Example of one data point: {'stepId': '5c8a78336d41a10da4f730ef', 'questionId': '5c8a78336d41a10da4f730f0', 'answerValue': '', 'answerId': '5c8a78336d41a10da4f730f2', 'answerTypeId': 'Answer'}

Lets try to create this into a dataframe and view it better.

In [79]:
sample_df = pd.DataFrame(sample_json)
sample_df.head()

,stepId,questionId,answerValue,answerId,answerTypeId
0,5c8a78336d41a10da4f730ef,5c8a78336d41a10da4f730f0,,5c8a78336d41a10da4f730f2,Answer
1,6507da8d9e117216630ef7ed,6507de7e9e117216630ef7f2,emilija+100_L8gA@bss.mk,,Answer
2,6507dfbb9e117216630ef7f3,6507e0219e117216630ef7f5,3138,,Answer
3,5c8a78336d41a10da4f733ce,5c8a78336d41a10da4f733d8,Eme,,Answer
4,5c8a78336d41a10da4f733ce,5c8a78336d41a10da4f733e2,Jankova,,Answer

Since each visitor has multiple rows, lets try exploding the whole dataset with this data column.

In [80]:
# First parsing the json data under data column into parsed_data column
visitors['parsed_data'] = visitors['data'].apply(lambda x: json.loads(x)) 
visitors.head()

,email,gender,visitorId,data,parsed_data
0,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,"[{ ""stepId"" : ""5c8a78336d41a10da4f730ef"", ""que...","[{'stepId': '5c8a78336d41a10da4f730ef', 'quest..."
1,aleksandar.dimkov+mitt1_n5eA@bss.com.mk,M,67ada1ee197e604dd2722d1b,"[{ ""stepId"" : ""5c8a78336d41a10da4f730ef"", ""que...","[{'stepId': '5c8a78336d41a10da4f730ef', 'quest..."
2,daniela.p+150_YhiF@bss.com.mk,F,67b44fef197e604dd2722d3d,"[{ ""stepId"" : ""5c8a78336d41a10da4f730ef"", ""que...","[{'stepId': '5c8a78336d41a10da4f730ef', 'quest..."
3,tanja+182_jiPa@bss.com.mk,F,67b45018197e604dd2722d3e,"[{ ""stepId"" : ""5c8a78336d41a10da4f730ef"", ""que...","[{'stepId': '5c8a78336d41a10da4f730ef', 'quest..."
4,aleksandar.dimkov+mitt10_V0iB@bss.com.mk,M,67b5f1392d21f543a10965f1,"[{ ""stepId"" : ""5c8a78336d41a10da4f730ef"", ""que...","[{'stepId': '5c8a78336d41a10da4f730ef', 'quest..."

In [81]:
# Removing the bulky data column as we are anyway exploding now.
exploded_visitors = visitors.explode('parsed_data').drop("data", axis=1).copy()
exploded_visitors.head()

,email,gender,visitorId,parsed_data
0,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,"{'stepId': '5c8a78336d41a10da4f730ef', 'questi..."
0,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,"{'stepId': '6507da8d9e117216630ef7ed', 'questi..."
0,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,"{'stepId': '6507dfbb9e117216630ef7f3', 'questi..."
0,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,"{'stepId': '5c8a78336d41a10da4f733ce', 'questi..."
0,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,"{'stepId': '5c8a78336d41a10da4f733ce', 'questi..."

In [82]:
# Unpacking and extracting individual key-value pairs from parsed_data into separate columns 
# Refer to this template from earlier - {'stepId': '5c8a78336d41a10da4f730ef', 'questionId': '5c8a78336d41a10da4f730f0', 'answerValue': '', 'answerId': '5c8a78336d41a10da4f730f2', 'answerTypeId': 'Answer'}

exploded_visitors['stepId'] = exploded_visitors['parsed_data'].apply(lambda x: x.get('stepId'))
exploded_visitors['questionId'] = exploded_visitors['parsed_data'].apply(lambda x: x.get('questionId'))
exploded_visitors['answerValue'] = exploded_visitors['parsed_data'].apply(lambda x: x.get('answerValue'))
exploded_visitors['answerId'] = exploded_visitors['parsed_data'].apply(lambda x: x.get('answerId'))
exploded_visitors['answerTypeId'] = exploded_visitors['parsed_data'].apply(lambda x: x.get('answerTypeId'))

# Removing the parsed_data column as we have already extracted each field now.
exploded_visitors.drop("parsed_data", axis=1, inplace=True)

exploded_visitors.head()

,email,gender,visitorId,stepId,questionId,answerValue,answerId,answerTypeId
0,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,5c8a78336d41a10da4f730ef,5c8a78336d41a10da4f730f0,,5c8a78336d41a10da4f730f2,Answer
0,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,6507da8d9e117216630ef7ed,6507de7e9e117216630ef7f2,emilija+100_L8gA@bss.mk,,Answer
0,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,6507dfbb9e117216630ef7f3,6507e0219e117216630ef7f5,3138,,Answer
0,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,5c8a78336d41a10da4f733ce,5c8a78336d41a10da4f733d8,Eme,,Answer
0,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,5c8a78336d41a10da4f733ce,5c8a78336d41a10da4f733e2,Jankova,,Answer

Now that we have the visitor data in a readable way, lets try to join it with the question and answer datasets

#### Joining with questions and answers

In [85]:
final_df = exploded_visitors.merge(answers, on=['answerId', 'questionId'], how='left').merge(questions, on=['questionId', 'stepId'], how='left')
final_df.head()

,email,gender,visitorId,stepId,questionId,answerValue,answerId,answerTypeId,answer,questionTypeId,question
0,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,5c8a78336d41a10da4f730ef,5c8a78336d41a10da4f730f0,,5c8a78336d41a10da4f730f2,Answer,NaN,NaN,NaN
1,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,6507da8d9e117216630ef7ed,6507de7e9e117216630ef7f2,emilija+100_L8gA@bss.mk,,Answer,NaN,NaN,NaN
2,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,6507dfbb9e117216630ef7f3,6507e0219e117216630ef7f5,3138,,Answer,NaN,NaN,NaN
3,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,5c8a78336d41a10da4f733ce,5c8a78336d41a10da4f733d8,Eme,,Answer,NaN,NaN,NaN
4,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,5c8a78336d41a10da4f733ce,5c8a78336d41a10da4f733e2,Jankova,,Answer,NaN,NaN,NaN

Using the parse_visitors function in code/data_cleaning/

In [91]:
%pwd

'd:\\ITE-data-science-assignment\\code'

In [ ]:
from data_cleaning.parse_visitors import parse_visitor_data

parsed_df = parse_visitor_data(visitors, answers, questions)
parsed_df.head()

,email,gender,visitorId,stepId,questionId,answerValue,answerId,answerTypeId,answer,questionTypeId,question
0,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,5c8a78336d41a10da4f730ef,5c8a78336d41a10da4f730f0,,5c8a78336d41a10da4f730f2,Answer,NaN,NaN,NaN
1,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,6507da8d9e117216630ef7ed,6507de7e9e117216630ef7f2,emilija+100_L8gA@bss.mk,,Answer,NaN,NaN,NaN
2,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,6507dfbb9e117216630ef7f3,6507e0219e117216630ef7f5,3138,,Answer,NaN,NaN,NaN
3,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,5c8a78336d41a10da4f733ce,5c8a78336d41a10da4f733d8,Eme,,Answer,NaN,NaN,NaN
4,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,5c8a78336d41a10da4f733ce,5c8a78336d41a10da4f733e2,Jankova,,Answer,NaN,NaN,NaN